const test=require('node:test'),assert=require('node:assert/strict'),vm=require('node:vm'),fs=require('node:fs');
const source=fs.readFileSync(require('node:path').join(__dirname,'../email-session.js'),'utf8');
function setup(fetch,store=new Map()) {const events={};const win={addEventListener:(n,fn)=>events[n]=fn};const ctx={window:win,navigator:{},localStorage:{getItem:k=>store.get(k)||null,setItem:(k,v)=>store.set(k,v),removeItem:k=>store.delete(k)},fetch,Date,JSON,Set,Error};vm.runInNewContext(source,ctx);return {api:win.KMEmailSession,store,events};}
const data={access_token:'site-access',refresh_token:'site-refresh',expires_at:Date.now()/1000+3600};
const response=(body,status=200)=>({ok:status<400,status,json:async()=>body});
test('sign in persists only site session, not password or email',async()=>{const x=setup(async()=>response({...data,user:{email:'admin@example.com'}}));await x.api.signIn('admin@example.com','never-store');assert.equal(x.api.has(),true);const stored=[...x.store.values()][0];assert.ok(!stored.includes('never-store'));assert.ok(!stored.includes('admin@example.com'));assert.deepEqual(Object.keys(JSON.parse(stored)).sort(),['access_token','expires_at','refresh_token']);});
test('new page restores session without password',async()=>{const x=setup(async()=>response(data));await x.api.signIn('a','p');let authorization;const y=setup(async(url,opts)=>{authorization=opts.headers.Authorization;return response({accounts:[]});},x.store);await y.api.api('list');assert.equal(authorization,'Bearer site-access');});
test('expired session refreshes before calling backend',async()=>{const calls=[];const x=setup(async(url)=>{calls.push(url);return response(url.includes('grant_type=password')?{...data,expires_at:1}:url.includes('refresh_token')?{...data,access_token:'renewed'}:{accounts:[]});});await x.api.signIn('a','p');await x.api.api('list');assert.equal(calls.filter(u=>u.includes('refresh_token')).length,1);assert.ok([...x.store.values()][0].includes('renewed'));});
test('temporary refresh errors do not destroy saved session',async()=>{let count=0;const x=setup(async()=>++count===1?response({...data,expires_at:1}):response({},503));await x.api.signIn('a','p');await assert.rejects(x.api.api('list'));assert.equal(x.api.has(),true);});
test('revoked refresh token clears saved session',async()=>{let count=0;const x=setup(async()=>++count===1?response({...data,expires_at:1}):response({},400));await x.api.signIn('a','p');await assert.rejects(x.api.api('list'));assert.equal(x.api.has(),false);});
test('logout clears browser access even if server is offline',async()=>{let count=0;const x=setup(async()=>{if(++count===1)return response(data);throw Error('offline');});await x.api.signIn('a','p');await x.api.signOut();assert.equal(x.api.has(),false);});
