import test from 'node:test';import assert from 'node:assert/strict';
import {syncHandler,metadata,historyIDs} from '../supabase/functions/_shared/sync.mjs';
const msg={id:'m1',threadId:'t1',historyId:'90071992547409999',internalDate:'1760000000000',snippet:'<script>not HTML</script>',labelIds:['INBOX','UNREAD'],payload:{headers:[{name:'From',value:'A <a@example.com>'},{name:'To',value:'"Last, First" <b@example.com>'},{name:'Subject',value:'Subject'},{name:'Message-ID',value:'<rfc-id>'},{name:'References',value:'<first> <second>'}]}};
function fixture(state={phase:'idle'},options={}){
 const calls=[];let committed;const handler=syncHandler({config:{origin:'https://site.example',clientId:'id',clientSecret:'secret'},authenticate:async()=>({id:'user',session_id:'session'}),
 rpc:async(action,user,co,data,proc)=>{calls.push({action,co,data,proc});if(action==='claim')return {lease_id:'lease',state};if(action==='credentials')return {access_token:'token',refresh_token:'refresh',revision:1,expires_at:'2099-01-01'};if(action==='commit'){committed=data;return {done:data.state.phase==='idle',processed:data.messages.length,total:1};}if(action==='list')return {messages:[]};return {ok:true};},
 fetch:async url=>{const path=new URL(url).pathname;return new Response(JSON.stringify(path.endsWith('/profile')?{emailAddress:'hamateeletroinfo@gmail.com',historyId:'baseline'}:path.endsWith('/history')?{historyId:'latest'}:path.endsWith('/messages')?{messages:[{id:'m1'}]}:msg));},...options});
 return {handler,calls,get committed(){return committed;}};
}
const req=(action='sync',company='HAMATE')=>new Request('https://backend.example',{method:'POST',headers:{Origin:'https://site.example'},body:JSON.stringify({action,company})});
test('metadata preserves string history IDs and recipient headers',()=>{const m=metadata(msg);assert.equal(m.history_id,'90071992547409999');assert.deepEqual(m.recipients,['"Last, First" <b@example.com>']);assert.equal(m.is_read,false);assert.deepEqual(m.reference_ids,['<first>','<second>']);assert.equal(m.preview,'<script>not HTML</script>');assert.ok(!('body' in m));});
test('labels reflect read state and inbox removal',()=>{assert.equal(metadata({...msg,labelIds:['INBOX']}).is_read,true);assert.equal(metadata({...msg,labelIds:[]}).in_inbox,false);assert.equal(metadata({...msg,labelIds:['INBOX','TRASH']}).in_inbox,false);});
test('history deduplicates additions deletions and label changes',()=>assert.deepEqual(historyIDs({history:[{messages:[{id:'a'}],messagesAdded:[{message:{id:'a'}}],labelsRemoved:[{message:{id:'b'}}],messagesDeleted:[{message:{id:'c'}}]}]}).sort(),['a','b','c']));
test('first full batch records generation and starts history catch-up',async()=>{const f=fixture();assert.equal((await f.handler(req())).status,200);assert.equal(f.committed.full_complete,true);assert.equal(f.committed.state.phase,'history');assert.equal(f.committed.state.cursor,'baseline');assert.equal(f.committed.messages[0].gmail_message_id,'m1');assert.ok(f.committed.generation);});
test('full pagination does not complete prematurely',async()=>{const f=fixture({phase:'full',generation:'generation',baseline:'b',page_token:'p'},{fetch:async url=>new Response(JSON.stringify(new URL(url).pathname.endsWith('/messages')?{messages:[{id:'m1'}],nextPageToken:'next'}:msg))});await f.handler(req());assert.equal(f.committed.full_complete,false);assert.equal(f.committed.state.page_token,'next');});
test('expired history restarts full scan without deleting messages',async()=>{const f=fixture({phase:'history',cursor:'old'},{fetch:async()=>new Response('{}',{status:404})});await f.handler(req());assert.deepEqual(f.committed.state,{phase:'full'});assert.deepEqual(f.committed.messages,[]);assert.equal(f.committed.full_complete,undefined);});
test('history applies changes before advancing cursor',async()=>{const f=fixture({phase:'history',cursor:'old'},{fetch:async url=>new Response(JSON.stringify(url.includes('/history?')?{history:[{labelsRemoved:[{message:{id:'m1'}}]}],historyId:'new'}:{...msg,labelIds:[]}))});await f.handler(req());assert.equal(f.committed.messages[0].in_inbox,false);assert.deepEqual(f.committed.state,{phase:'idle',cursor:'new'});});
test('large history pages resume pending IDs in batches of 20',async()=>{const f=fixture({phase:'history',cursor:'old',pending:Array.from({length:25},(_,i)=>'m'+i),latest:'new',page_token:null});await f.handler(req());assert.equal(f.committed.messages.length,20);assert.equal(f.committed.state.pending.length,5);assert.equal(f.committed.state.phase,'history');});
test('history next page preserved until processed',async()=>{const f=fixture({phase:'history',cursor:'old'},{fetch:async()=>new Response(JSON.stringify({history:[],nextPageToken:'next',historyId:'new'}))});await f.handler(req());assert.equal(f.committed.state.phase,'history');assert.equal(f.committed.state.page_token,'next');});
test('message deleted between list and fetch becomes tombstone',async()=>{const f=fixture({phase:'full',generation:'g',baseline:'b'},{fetch:async url=>url.includes('/messages?')?new Response(JSON.stringify({messages:[{id:'missing'}]})):new Response('{}',{status:404})});await f.handler(req());assert.deepEqual(f.committed.messages,[{gmail_message_id:'missing',in_inbox:false}]);});
test('transient errors release lease without advancing cursor',async()=>{const f=fixture({phase:'history',cursor:'old'},{fetch:async()=>new Response('{}',{status:429})});assert.equal((await f.handler(req())).status,502);assert.ok(f.calls.some(c=>c.action==='fail'));assert.equal(f.committed,undefined);});
test('no session cannot read or sync',async()=>{const {Failure}=await import('../supabase/functions/_shared/oauth.mjs');const f=fixture(undefined,{authenticate:async()=>{throw new Failure('login_required',401);}});assert.equal((await f.handler(req('messages'))).status,401);assert.equal(f.calls.length,0);});
test('busy lease does not fetch Google',async()=>{let fetched=false;const f=fixture(undefined,{rpc:async()=>({error:'sync_busy'}),fetch:async()=>{fetched=true;}});assert.equal((await f.handler(req())).status,409);assert.equal(fetched,false);});
test('company access rejected before credentials',async()=>{let count=0;const f=fixture(undefined,{rpc:async()=>{count++;return {error:'not_authorized'};}});assert.equal((await f.handler(req())).status,403);assert.equal(count,1);});
test('wrong Gmail account rejected on full import',async()=>{const f=fixture(undefined,{fetch:async()=>new Response(JSON.stringify({emailAddress:'gaditaempreendimentos@gmail.com'}))});assert.equal((await f.handler(req())).status,400);assert.equal(f.committed,undefined);});
test('listing never fetches Google or retrieves tokens',async()=>{const f=fixture();await f.handler(req('messages'));assert.deepEqual(f.calls.map(c=>c.action),['list']);});
