import test from 'node:test';
import assert from 'node:assert/strict';
import {handlers,MAILBOXES,GMAIL_SCOPE,Failure,random,stateHash,verifyIdentity,authorizationURL} from '../supabase/functions/_shared/oauth.mjs';
const config={origin:'https://site.example',clientId:'client',clientSecret:'secret-never-returned',redirectUri:'https://backend.example/callback'};
function fixture(overrides={}){
 const calls=[];const flow={company:'HAMATE',email:MAILBOXES.HAMATE,user_id:'user',session_id:'session',flow_id:'flow',verifier:'verifier',nonce:'nonce'};
 const token={access_token:'private-access',refresh_token:'private-refresh',id_token:'private-id',scope:`openid email ${GMAIL_SCOPE}`,expires_in:3600,token_type:'Bearer'};
 const deps={config,authenticate:async()=>({id:'user',session_id:'session'}),verifyIdToken:async()=>({sub:'google-id',email:MAILBOXES.HAMATE,email_verified:true,nonce:'nonce'}),
  rpc:async(action,user,co,data)=>{calls.push({action,user,co,data});if(action==='consume')return flow;if(action==='accounts')return [{company:'HAMATE',email:MAILBOXES.HAMATE,status:'connected'}];if(action==='credentials')return {access_token:'private-access',refresh_token:'private-refresh',expires_at:new Date(Date.now()+3600000).toISOString(),revision:1};return {ok:true};},
  fetch:async(url)=>new Response(JSON.stringify(url.includes('/token')?token:{emailAddress:MAILBOXES.HAMATE}),{status:200}),...overrides};
 return {...handlers(deps),calls,flow,token};
}
const req=(action,co='HAMATE',origin=config.origin)=>new Request('https://backend.example/accounts',{method:'POST',headers:{Origin:origin,'Content-Type':'application/json'},body:JSON.stringify({action,company:co})});
const cb=()=>new Request(`https://backend.example/callback?state=${'a'.repeat(43)}&code=private-code`);
test('cryptographically random states and SHA256 digest',async()=>{assert.equal(random().length,43);assert.notEqual(random(),random());assert.equal((await stateHash('a')).length,64);});
test('authorization uses read-only Gmail, offline access, PKCE and exact mailbox',()=>{const u=new URL(authorizationURL(config,{company:'GADITA',state:'s',nonce:'n',challenge:'c'}));assert.equal(u.searchParams.get('login_hint'),MAILBOXES.GADITA);assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal(u.searchParams.get('access_type'),'offline');assert.ok(!u.href.includes('gmail.modify'));assert.ok(!u.href.includes(config.clientSecret));});
for(const payload of [{email:MAILBOXES.GADITA,email_verified:true,sub:'x',nonce:'nonce'},{email:MAILBOXES.HAMATE,email_verified:false,sub:'x',nonce:'nonce'},{email:MAILBOXES.HAMATE,email_verified:true,sub:'x',nonce:'other'}])test('reject wrong company, unverified email or nonce: '+JSON.stringify(payload),()=>assert.throws(()=>verifyIdentity(payload,{company:'HAMATE',nonce:'nonce'})));
test('pin Google subject on reconnect',()=>assert.throws(()=>verifyIdentity({email:MAILBOXES.HAMATE,email_verified:true,sub:'new',nonce:'n'},{company:'HAMATE',nonce:'n',google_account_id:'old'})));
test('unauthenticated request rejected before database',async()=>{const f=fixture({authenticate:async()=>{throw new Failure('login_required',401);}});assert.equal((await f.accounts(req('list'))).status,401);assert.equal(f.calls.length,0);});
test('unknown company and hostile origin rejected',async()=>{const f=fixture();assert.equal((await f.accounts(req('connect','OTHER'))).status,400);assert.equal((await f.accounts(req('list','HAMATE','https://evil.example'))).status,403);assert.equal(f.calls.length,0);});
test('insufficient company permission rejected',async()=>{const f=fixture({rpc:async()=>({error:'not_authorized'})});assert.equal((await f.accounts(req('connect'))).status,403);});
test('connect only returns authorization URL, never verifier or client secret',async()=>{const f=fixture();const res=await f.accounts(req('connect','GADITA'));assert.equal(res.status,200);const body=await res.json();assert.deepEqual(Object.keys(body),['authorization_url']);assert.equal(new URL(body.authorization_url).searchParams.get('login_hint'),MAILBOXES.GADITA);assert.ok(!JSON.stringify(body).includes(f.calls[0].data.verifier));assert.ok(!JSON.stringify(body).includes(config.clientSecret));});
test('successful callback saves tokens only through backend',async()=>{const f=fixture();const res=await f.callback(cb());assert.equal(res.status,303);assert.equal(res.headers.get('Location'),config.origin+'/gmail.html?oauth=connected');const finish=f.calls.find(c=>c.action==='finish');assert.equal(finish.co,'HAMATE');assert.equal(finish.data.refresh_token,'private-refresh');assert.equal(await res.text(),'');assert.equal(res.headers.get('Cache-Control'),'no-store');});
test('wrong mailbox never persists tokens',async()=>{const f=fixture({verifyIdToken:async()=>({sub:'x',nonce:'nonce',email:MAILBOXES.GADITA,email_verified:true})});assert.match((await f.callback(cb())).headers.get('Location'),/account_mismatch$/);assert.ok(!f.calls.some(c=>c.action==='finish'));});
test('Google signature/audience failure does not persist tokens',async()=>{const f=fixture({verifyIdToken:async()=>{throw new Error('signature failed secret');}});assert.match((await f.callback(cb())).headers.get('Location'),/oauth=failed$/);assert.ok(!f.calls.some(c=>c.action==='finish'));});
for(const reason of ['expired_state','invalid_state','superseded','not_authorized'])test('callback stops on '+reason,async()=>{let requests=0;const f=fixture({rpc:async()=>({error:reason}),fetch:async()=>{requests++;throw Error();}});assert.match((await f.callback(cb())).headers.get('Location'),new RegExp(reason+'$'));assert.equal(requests,0);});
test('missing refresh token does not mark connected',async()=>{const f=fixture();delete f.token.refresh_token;assert.match((await f.callback(cb())).headers.get('Location'),/missing_refresh_token$/);assert.ok(!f.calls.some(c=>c.action==='finish'));});
test('missing Gmail consent does not mark connected',async()=>{const f=fixture();f.token.scope='openid email';assert.match((await f.callback(cb())).headers.get('Location'),/missing_scope$/);assert.ok(!f.calls.some(c=>c.action==='finish'));});
test('denial consumes state without token exchange',async()=>{const f=fixture({fetch:async()=>{throw Error('must not call');}});const response=await f.callback(new Request(`https://backend.example?state=${'a'.repeat(43)}&error=access_denied`));assert.match(response.headers.get('Location'),/consent_denied$/);assert.equal(f.calls[0].action,'consume');});
test('profile mismatch cannot mark connected',async()=>{const f=fixture();const g=fixture({fetch:async url=>new Response(JSON.stringify(url.includes('/token')?f.token:{emailAddress:MAILBOXES.GADITA}))});assert.match((await g.callback(cb())).headers.get('Location'),/account_mismatch$/);assert.ok(!g.calls.some(c=>c.action==='finish'));});
test('refresh failure marks only selected company for reauthorization',async()=>{const calls=[];const f=fixture({rpc:async(action,user,co,data)=>{calls.push({action,co,data});return action==='credentials'?{refresh_token:'private',revision:9,expires_at:'2000-01-01'}:{ok:true};},fetch:async()=>new Response(JSON.stringify({error:'invalid_grant'}),{status:400})});assert.equal((await f.accounts(req('check','GADITA'))).status,502);assert.deepEqual(calls.find(c=>c.action==='invalid'),{action:'invalid',co:'GADITA',data:{revision:9}});});
test('refresh preserves existing token when provider omits refresh token',async()=>{let count=0;const calls=[];const f=fixture({rpc:async(action,user,co,data)=>{calls.push({action,data});if(action==='credentials')return {refresh_token:'old',access_token:'private',revision:++count,expires_at:'2000-01-01'};if(action==='accounts')return [];return {ok:true};}});assert.equal((await f.accounts(req('check'))).status,200);assert.ok(calls.some(c=>c.action==='refresh'));assert.ok(calls.some(c=>c.action==='checked'));});
